### PR TITLE
Mizool Relicensing

### PR DESCRIPTION
**Pull request by bannmann**

### CODE REVIEW

**Comment by bannmann** [comment]
Note: we found that relicensing was simpler than we thought as the only code copied from elsewhere was removed in 2017 with commit 184f9482d3be59294996ce6dee2653aabcb30917.

**Comment by bannmann** [comment]
@schroenser: @lesmou suggested that for this particular PR, we add Yombu to the list of people who are FYI'd.

**Review by schroenser — APPROVED** [review]

**Comment by schroenser** [comment]
Note that I've chosen to ignore the 14 Code Smells, as they are not introduced by this change.

**Comment by schroenser** [comment]
FYI: @gregorxiv @JanDoerrenhaus @Yombu

**Pull request merged**
